nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v2.4.0/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
cacheFolder: "${HOME}/.yarn/cache"
enableColors: true
enableScripts: false
enableTelemetry: false
