version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo Getting dependencies
      - go get -u golang.org/x/lint/golint
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure

  pre_build:
    commands:
      - echo Linting
      - golint -set_exit_status
      # - echo Testing
      # - go test

  build:
    commands:
      - echo Compiling
      - go build -o app main.go

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app
